### ISSUE TITLE
Generated client doesn't support browsers

### ISSUE THREAD

**Issue by delaneyj** [hopin-team/twirp-ts#10] opened 2021-06-29 19:19 UTC
Currently using Buffer in http.ts which is causing it to fail in browser. Used previous TS clients for Twirp in browser for float heavy realtime communciation and its was a 6x speed improvement. Possible to use UInt8Array directly?

`// const requestData = contentType === "application/protobuf" ? Buffer.from(data) : JSON.stringify(data);`

**Comment by delaneyj** [comment] 2021-06-29 19:28
Same with usage of `url`, https://developer.mozilla.org/en-US/docs/Web/API/URL is builtin to the browser nowadays

**Comment by delaneyj** [comment] 2021-06-29 19:37
Ok I'm dense.. you literally named it  `NodeHttpRPC`.  I'll make a browser compatible version below once I write it and hopefull you can include some versoin of it.

**Comment by fenos** [comment] 2021-06-29 21:36
@delaneyj Thanks for your great feedback!

Sure, I agree that the `Rpc` interface should be exported. I'll patch that shortly.

However, at the current stage of `twirp-ts` it focuses more on the backend side of things, in fact, I don't think that the generated code is compatible with the browser as of now. 

The main reason is that the client and server code are generated in the same file, and that file is importing from `ts-twirp` where `ts-twirp` imports node-specific libraries.

One way of making the library browser compatible is to generate the client as a stand-alone file. 

I wouldn't want to include `axios` as a dependency of the project, maybe as a separate package could be more appropriate something like: `twirp-ts-axios` for browser spefici use, which implements the `Rpc` interface.

**Comment by delaneyj** [comment] 2021-06-29 23:51
Agreed for the most part.  I will say with the above it is working in both node & browser.  I worry a little about having multiple server/client as the whole point of twirp is the simplicity.  I know larrymeyers/twirp relied on it and for client it worked great.  I guess my question is what are you gaining by not supporting a cross platform approach?

**Comment by miri1299** [comment] 2021-07-20 08:09
I legitimately spent a good 2 hours trying to figure this out. I shamelessly copy/pasted the browser version here. Using Twirp as an interface between React SPAs and your backend can be super powerful. I'd really prefer that the library natively support the browser as well. I did finally get it working though!

**Comment by jeffreylo** [comment] 2021-07-24 02:32
> Agreed for the most part. I will say with the above it is working in both node & browser. I worry a little about having multiple server/client as the whole point of twirp is the simplicity. I know larrymeyers/twirp relied on it and for client it worked great. I guess my question is what are you gaining by not supporting a cross platform approach?

Were you able to get the generated protobuf client working after your proposed changes? Any examples to share? I’ve been working on trying to get this working in #17; the JSON client seems to work OK after removing any dependency on `twirp-ts` itself (due to the `http` dependencies), but not getting the same with the Protobuf client.

**Comment by jeffreylo** [comment] 2021-07-24 02:32
> Agreed for the most part. I will say with the above it is working in both node & browser. I worry a little about having multiple server/client as the whole point of twirp is the simplicity. I know larrymeyers/twirp relied on it and for client it worked great. I guess my question is what are you gaining by not supporting a cross platform approach?
— @delaneyj 

Were you able to get the generated protobuf client working after your proposed changes? Any examples to share? I’ve been working on trying to get this working in #17; the JSON client seems to work OK after removing any dependency on `twirp-ts` itself (due to the `http` dependencies), but not getting the same with the Protobuf client.

**Comment by fenos** [comment] 2021-07-25 10:03
Hey guys, now that #17 has been merged you can generate the client code separately from the server. 
Which is taking us one step forward to fully support the browser.

The only thing that doesn't come out of the box is the actual `Rpc` implementation.

I gave it more thinking on how we can fully support the browser providing an `axios` or `fetch` implementation and I believe that having a second package ex: `twirp-ts-browser` or `twirp-ts-client` is the way to go since if we include it in this package we end up having the problem of importing `node` specific modules.

I was also considering going mono repo and divide the packages this way:

- `@twirp-ts/server`     // node js server
- `@twirp-ts/client`      // client implementation with axios (server and client compatible)
- `@twirp-ts/core`       // shared code between client and server (ex; error)

I'm still wondering if that is the right way to go... 

I'm still very keen to fully support the browser

**Comment by miri1299** [comment] 2021-07-25 22:44
> Hey guys, now that #17 has been merged you can generate the client code separately from the server.
> Which is taking us one step forward to fully support the browser.
> 
> The only thing that doesn't come out of the box is the actual `Rpc` implementation.
> 
> I gave it more thinking on how we can fully support the browser providing an `axios` or `fetch` implementation and I believe that having a second package ex: `twirp-ts-browser` or `twirp-ts-client` is the way to go since if we include it in this package we end up having the problem of importing `node` specific modules.
> 
> I was also considering going mono repo and divide the packages this way:
> 
> * `@twirp-ts/server`     // node js server
> * `@twirp-ts/client`      // client implementation with axios (server and client compatible)
> * `@twirp-ts/core`       // shared code between client and server (ex; error, plugin)
> 
> I'm still wondering if that is the right way to go...
> 
> I'm still very keen to fully support the browser

I think by bundling them into a mono-repo you do help address dependency issues. But at the same time I think you might introduce an issue if anything in client ends up depending on node vs plain ES / TS. The weird thing I ran into was that apparently in Chrome + Mozilla the `URL` class is very different than the one vended by Node. So while the include works, it doesn't have the right methods or constructors so it doesn't really end up being compatible. 


> > Agreed for the most part. I will say with the above it is working in both node & browser. I worry a little about having multiple server/client as the whole point of twirp is the simplicity. I know larrymeyers/twirp relied on it and for client it worked great. I guess my question is what are you gaining by not supporting a cross platform approach?
> > — @delaneyj
> 
> Were you able to get the generated protobuf client working after your proposed changes? Any examples to share? I’ve been working on trying to get this working in #17; the JSON client seems to work OK after removing any dependency on `twirp-ts` itself (due to the `http` dependencies), but not getting the same with the Protobuf client.

I have been able to use the "Browser Client" to successfully interact with a Twirp service I've written in Go. I have a react SPA (Twitch extension) which uses the JSON client and the Browser Client as a transport. It all works wonderfully and has _dramatically_ reduced the amount of time I spend in boilerplate for the data interface in the SPA itself. 

I'm really excited about the future of this library. It seems incredibly powerful. Happy to provide feedback if you have specific questions on the browser support side.

**Comment by jeffreylo** [comment] 2021-07-28 04:22
> I have been able to use the "Browser Client" to successfully interact with a Twirp service I've written in Go. I have a react SPA (Twitch extension) which uses the JSON client and the Browser Client as a transport. It all works wonderfully and has dramatically reduced the amount of time I spend in boilerplate for the data interface in the SPA itself.

@miri1299, how about the protobuf version of the client?

**Comment by miri1299** [comment] 2021-07-28 04:24
> > I have been able to use the "Browser Client" to successfully interact with a Twirp service I've written in Go. I have a react SPA (Twitch extension) which uses the JSON client and the Browser Client as a transport. It all works wonderfully and has dramatically reduced the amount of time I spend in boilerplate for the data interface in the SPA itself.
> 
> @miri1299, how about the protobuf version of the client?

I swapped it out and I was getting issues with marshaling data from the wire protocol. I'm not exactly sure where. I don't really "need" the speed of protobuf for what I'm doing so just using JSON is fine for me for the moment being. That said, dropping in the Proto client did start to produce errors. So at a bare minimum there's something fishy going on there. I may dig into it later.

**Comment by fenos** [comment] 2021-07-28 08:44
@jeffreylo the axios client in the example folder should work with protobuf just fine for the browser,
Feel free to open an issue if you have any specific problem, i'd be happy to help

**Comment by jeffreylo** [comment] 2021-08-04 21:09
@fenos apologies for the delay. Here’s a repo to reproduce the error I’m seeing: https://github.com/jeffreylo/twirp-ts-protobuf

**Comment by fenos** [comment] 2021-08-10 09:53
@jeffreylo thanks for the reproduction, 

I'm not entirely sure why you get that error just yet, somehow the `protobuf-ts` - `toBinary()` function doesn't like `ArrayBuffer` 

A workaround that is to actually use `Buffer.from(response.data)` before returning in the promise.

https://github.com/jeffreylo/twirp-ts-protobuf/blob/main/src/client.ts#L28

that worked for me

**Comment by sgraham785** [comment] 2021-09-01 22:56
> @jeffreylo thanks for the reproduction,
> 
> I'm not entirely sure why you get that error just yet, somehow the `protobuf-ts` - `toBinary()` function doesn't like `ArrayBuffer`
> 
> A workaround is to actually use `Buffer.from(response.data)` before returning in the promise.
> 
> https://github.com/jeffreylo/twirp-ts-protobuf/blob/main/src/client.ts#L28
> 
> that worked for me
> 
> Something like this:
> 
> ```ts
> .then((response) => {
>      if (contentType === "application/json") {
>          return response.data
>      }
>      return Buffer.from( response.data);
> });
> ```

Also, you may need to `npm install buffer` and add `import { Buffer } from 'buffer'` to that client.ts, depends on how your polyfill is set up. 

Thanks for the workaround!

**Closed** 2021-11-12 10:10 UTC
